# Generated by Django 2.0 on 2017-12-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_auto_20171206_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShackProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_loeffelhardt_account', models.BooleanField(default=False)),
                ('has_matomat_key', models.BooleanField(default=False)),
                ('has_metro_card', models.BooleanField(default=False)),
                ('has_safe_key', models.BooleanField(default=False)),
                ('has_selgros_card', models.BooleanField(default=False)),
                ('has_shack_iron_key', models.BooleanField(default=False)),
                ('has_snackomat_key', models.BooleanField(default=False)),
                ('is_keyholder', models.BooleanField(default=False)),
                ('signed_DSV', models.BooleanField(default=False)),
                ('ssh_public_key', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_shack', to='members.Member')),
            ],
        ),
    ]
