# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 13:30
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('byro_shackspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shackprofile',
            name='member',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_shack', to='members.Member'),
        ),
    ]
